<testng-results>
  <reporter-output>
  </reporter-output>
  <suite name="Custom suite">
    <groups>
    </groups>
    <test name="bsp2">
      <class name="test.data.AcoTest">
        <test-method status="FAIL" signature="should_initiate_multiple_ants()" name="should_initiate_multiple_ants" duration-ms="33" started-at="2009-12-18T21:43:56Z" finished-at="2009-12-18T21:43:56Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.RangeCheck(ArrayList.java:547)
	at java.util.ArrayList.get(ArrayList.java:322)
	at logic.Aco.find_best_tree(Aco.java:70)
	at logic.Aco.update_pheromone(Aco.java:80)
	at logic.Aco.run(Aco.java:32)
	at test.data.AcoTest.should_initiate_multiple_ants(AcoTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:607)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:956)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:759)
	at org.testng.TestRunner.privateRun(TestRunner.java:592)
	at org.testng.TestRunner.run(TestRunner.java:486)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:332)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:327)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:299)
	at org.testng.SuiteRunner.run(SuiteRunner.java:204)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:867)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:832)
	at org.testng.TestNG.run(TestNG.java:748)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:79)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="before_method()" name="before_method" is-config="true" duration-ms="20" started-at="2009-12-18T21:43:56Z" finished-at="2009-12-18T21:43:56Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
